server:
  port : 8002
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  datasource:
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234